# General setting
is:
  keycloak:
    admin:
      user: admin
      password: admin

custom:
  urlKeycloakToken: http://localhost:8081/realms/master/protocol/openid-connect/token
  urlKeycloak: http://localhost:8081

# Keycloak settings
keycloak:
  realm: master
  auth-server-url: http://localhost:8081/auth
  ssl-required: none
  resource: is-keycloak
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  principal-attribute: preferred_username
